SET C51INC=D:\Program Files\keil_C51\C51\Inc;D:\Program Files\keil_C51\C51\Inc\Cast
SET C51LIB=D:\Program Files\keil_C51\C51\Lib
SET CPU_TYPE=R8051XC2
SET CPU_VENDOR=CAST, Inc.
SET UV2_TARGET=CA51FX
SET CPU_XTAL=0x016E3600
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\fm175xx.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\type_a.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\key.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\CA51F2~1.__I"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\BLUETO~1.__I"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\fifo.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\MAINHA~1.__I"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\proto.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\SYSTEM~1.__I"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\uart.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\rtc.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\spi.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\wdt.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\ts_api.__i"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\TS_SEV~1.__I"
"D:\Program Files\keil_C51\C51\BIN\C51.EXE" @".\Objects\blue_api.__i"
"D:\Program Files\keil_C51\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\Program Files\keil_C51\C51\BIN\LX51.EXE" @".\Objects\X10-KE~1.LNP"
"D:\Program Files\keil_C51\C51\BIN\OHX51.EXE" ".\Objects\X10-KeyBoard" HEX
make_bin.bat
